### ISSUE TITLE
Upgrade Python to 3.X

### ISSUE THREAD

**Issue by zenprox** [Technosoft2000/docker-sabnzbd#1]
First a Happy New Year!

nzbToMedia does not work anymore due to Python 2.7 EOL:
```
Please use a newer version of Python.
Python End-of-Life for current versions:
v2.7 in    0 days
v3.5 in  256 days
v3.6 in  722 days
v3.7 in 1273 days
v3.8 in 1748 days
Python 2.7 is no longer supported.
```
Please upgrade Python to 3.X

**Update - quick Workaround:**

Edit `eol.py ` in scripts folder
```python
PYTHON_EOL = {
    ...
    (2, 7): date('2020-01-01'),
    ...
}
```
to
```python
PYTHON_EOL = {
    ...
    (2, 7): date('2025-01-01'),
    ...
}
```

**Comment by Technosoft2000** [comment]
Hi @zenprox ,

happy new year too :)

Thanks for the hint, I'll try to upgrade to python 3 immediately.

**Comment by Technosoft2000** [comment]
Python 3.x is not officially supported by SABnzbd yet.

On their page I've found:
"SABnzbd requires Python 2.7.
Python 3.x is not supported. Check python version with python --version. "

I've tried to build a docker image to see what is happening when python 3 is used and got the following message:
```
[INFO] Launching SABnzbd ...
  File "/sabnzbd/app/SABnzbd.py", line 20
    print "Sorry, requires Python 2.7."
                                      ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Sorry, requires Python 2.7.")?
```

Therefore I'll try to patch nzbToMedia

**Comment by Technosoft2000** [comment]
Only the development branch supports python 3 -> https://github.com/sabnzbd/sabnzbd/issues/933
Therfore I've decided to test this one now :)

**Comment by Technosoft2000** [comment]
New version v1.4.0 is online https://hub.docker.com/r/technosoft2000/sabnzbd
Please try it and let me know if all works for you now :)

**Comment by zenprox** [comment]
> New version v1.4.0 is online https://hub.docker.com/r/technosoft2000/sabnzbd
> Please try it and let me know if all works for you now :)

Thank you! works like a charm 👍🏻
